### ISSUE TITLE
custom:my-slider-v2 not working on iOS?

### ISSUE THREAD

**Issue by AndyVRD** [AnthonMS/my-cards#26] opened 2022-07-02 20:11 UTC
Hi,

Thanks for the great v2 update. For some reason the slider can no longer be dragged from the HA iOS app? In the v1 version it was necessary to define the thumbWidth otherwise it was not able to slide. In the v2 update i see you now using styles so i made the thumb height a bit larger but sliding is still not working?

**Comment by AnthonMS** [comment] 2022-07-02 20:26
Hello, and thank you for trying the new slider and letting me know of an issue you are having.

The new slider does not rely upon the build in browser input range slider. This means that I control everything, down to what happens and where on user input. So that the regular slider only worked on thumb, was a limitation for the html input range element.

This means that to set the slider to only react on the thumb, then you have to set the config key 'allowTapping' to false. If this is set to true, then it will only react on the thumb. 
Is this the key you have set? If so, it might be bugging out on actual touch devices for this feature. I have not actually tested it on a touch device, only with a mouse.

**Comment by AndyVRD** [comment] 2022-07-02 20:30
Hi Anthon,

Thanks for the quick reply. I tested bot allowTapping true and false but whatever i try or set it's not reacting on any user input. Testing in Chrome, Firefox etc works indeed fine.

**Comment by AnthonMS** [comment] 2022-07-02 20:31
I am testing now. Are you using it vertically?

**Comment by AndyVRD** [comment] 2022-07-02 20:33
I tested both vertical and horizontal, seems that both are impacted by this bug?

**Comment by AnthonMS** [comment] 2022-07-02 20:34
Then it must be an IOS bug with both. On my android and in chrome touch sim it reacts fine on horizontal sliders, but very weird with vertical if at all.

**Comment by AndyVRD** [comment] 2022-07-02 20:37
If there is anything i can do to help you troubleshooting this on iOS le me know. If you have discord you can always add me.

AndyVR#1021

**Comment by AnthonMS** [comment] 2022-07-02 20:43
> If there is anything i can do to help you troubleshooting this on iOS le me know. If you have discord you can always add me.
> 
> AndyVR#1021

I think I will start out by fixing the touch bug in general, maybe that is the one causing issues for IOS devices? I don't really know. I'm pretty sure I tested vertical sliders on touch, so it must have been lost again on the way.

I don't know if I will work on it right now, I think I need a bit of a break to come back with a fresh pair of eyes later or maybe tomorrow. But this is certainly the first thing I will look at when I spin it up again, since I have just put my dashboard to use these cards and now I can't open or close the covers from the app. 

I will add you on discord and you are welcome to send anything you want to give me insight in your error, so it might help me when I get back to coding. :)

**Comment by AndyVRD** [comment] 2022-07-02 20:46
There is no need to hurry things up, take the time you need. You already did a great job on the v2 update and v1 is still working fine in the meanwhile. :)

Have a great weekend!

Kind regards
Andy

**Comment by Kmanggaard** [comment] 2022-07-03 12:34
I can confirm this. No response to touch on old iPad. If horizontal it will follow state, but in vertical any change in state wipes the lovelace view until refresh!

**Comment by AnthonMS** [comment] 2022-07-03 12:44
> I can confirm this. No response to touch on old iPad. If horizontal it will follow state, but in vertical any change in state wipes the lovelace view until refresh!

Both allowTapping=true and allowTapping=false works on IOS touch devices, right? As long as it's horizontal? (If allow tappin is true, you should be able to click anywhere on slider to set position. If false, you should only be allowed to drag by thumb.)
Does a horizontal flipped work as expected? And does an horizontal inverse? Just curious, I will start looking into it in a moment I think.

**Comment by AnthonMS** [comment] 2022-07-03 13:33
This is very weird. I started working on the issue, and I could replicate it by going to touch simulation on chrome. Then suddenly I couldn't replicate it anymore. It was minor the things I changed during this process, and it wasn't really because of this bug I changed them, it was just because I stumbled upon them.

I am sitting with my Android device on both chrome and in the app, and both seem to work as expected. I will try to install safari on my Android :unamused: just as a quick test. Then I will try to find some cross browser testing tool online. If anyone knows of a good one, let me know. Otherwise I will ask a coworker tomorrow. I know he has a good one he uses.

**Comment by AnthonMS** [comment] 2022-07-03 13:54
This should be resolved in the latest version.

Thanks for letting me know and standing by to help with some logs for debugging. This was fortunately just me having a brain fart and using touch position relative to page position instead of view position. So the numbers got all messed up when vertical sliders where on a page where you had scrolled.

**Closed by AnthonMS** 2022-07-03 13:54 UTC
Labels: bug, priority high

**Comment by AnthonMS** [comment] 2022-07-04 18:53
Btw, I have created a new issue for this #29
